### ISSUE TITLE
Problems when calling a contact.

### ISSUE THREAD

**Issue by sollaholla** [CamxxCore/iFruitContacts#10]
The phone pops up, and then immediately disappears, but the call is still ongoing.
Is this intended?

**Comment by sollaholla** [comment]
```
ifruit = new CustomiFruit();
var contact = new iFruitContact("Sollaholla's Vehicle Delivery", 21);
contact.Answered += Contact_Answered;
contact.DialTimeout = 3000;
contact.Icon = new ContactIcon("char_sasquatch");
ifruit.Contacts.Add(contact);
```

**Comment by sharppaul** [comment]
Check if the a contact with that index is already present, as this will cause them to call both persons and the game will decide which call puts away the phone.

**Comment by sollaholla** [comment]
@sharppaul That's not the problem :( I have my index very high to be sure of that (you can even see a gap between contacts until mine pops up). The problem is when i call it just instantly disappears.

**Comment by CamxxCore** [comment]
Hi sollaholla. The phone disappearing is not necessarily intended. I just never found a way to block the player input while selecting items in the menu. Since there is no event hooked up to the select action (from the point of view of the game) it just hides the phone since it doesn't know what else to do.

**Comment by sollaholla** [comment]
@CamxxCore Great answer! Thank you for the explanation! :+1:  I'm going to close this now, as it's not really a super bad bug.
